module.exports = {
	CREDENTIALS: "CREDENTIALS",
	ROOM_LENGTH: "ROOM_LENGTH",
	NOTIFICATION: "NOTIFICATION",
	NEW_PEER: "NEW_PEER",
	CHAT_MESSAGE: "CHAT_MESSAGE",
	DISCOVERY: "DISCOVERY",
	OFFER: "OFFER",
	ANSWER: "ANSWER",
};
